#!/bin/bash

get_free_memory_percentage() {
    total_mem=$(free | grep Mem | awk '{print $2}')
    free_mem=$(free | grep Mem | awk '{print $7}')
    
    free_percentage=$((free_mem * 100 / total_mem))
    echo $free_percentage
}

while true; do
    free_percentage=$(get_free_memory_percentage)
    sensor_info=$(sensors | awk '/^Package id 0:/ {temp=$4} /^fan1:/ {fan=$2} END {print temp " | " fan " RPM"}')

    echo "RAM ${free_percentage}% | $sensor_info"

    if [ "$free_percentage" -le 3 ]; then
        echo "Memory too low! Killing Process..."
        pkill -fi code
        pkill -fi FL64.exe
    fi

    sleep 1
done
