#!/bin/bash
set -e

IN="$1"
OUT="$2"

if [ -z "$IN" ] || [ -z "$OUT" ]; then
  echo "Usage: imgspoilerize input.png output.xcf" >&2
  exit 1
fi

gimp -i -b "
(let* (
  (img (car (gimp-file-load RUN-NONINTERACTIVE \"$IN\" \"$IN\")))
  (base (car (gimp-image-get-active-layer img)))
  (blur (car (gimp-layer-copy base TRUE)))
)
  (gimp-image-insert-layer img blur 0 -1)
  (plug-in-gauss RUN-NONINTERACTIVE img blur 30 30 0)
  (gimp-file-save RUN-NONINTERACTIVE img blur \"$OUT\" \"$OUT\")
)
" -b "(gimp-quit 0)" 2>/dev/null

